/**
 * Liability Disclaimer Modal
 * Mandatory acknowledgment required before each session
 */

import { useEffect, useState } from 'react'

interface LiabilityModalProps {
  onAcknowledge: () => void
}

export function LiabilityModal({ onAcknowledge }: LiabilityModalProps) {
  const [isVisible, setIsVisible] = useState(true)

  // Check if already acknowledged in this session
  useEffect(() => {
    const acknowledged = sessionStorage.getItem('liability-acknowledged')
    if (acknowledged === 'true') {
      setIsVisible(false)
    }
  }, [])

  const handleAcknowledge = () => {
    sessionStorage.setItem('liability-acknowledged', 'true')
    setIsVisible(false)
    onAcknowledge()
  }

  if (!isVisible) {
    return null
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-75 p-4">
      <div className="max-w-2xl w-full bg-white dark:bg-gray-800 rounded-lg shadow-xl p-6 md:p-8">
        <h2 className="text-2xl font-bold mb-4 text-gray-900 dark:text-white">
          Important Disclaimer
        </h2>

        <div className="space-y-4 text-gray-700 dark:text-gray-300 mb-6">
          <p>
            <strong>This is an AI-powered application.</strong> All outputs are generated by
            artificial intelligence and must be verified before use.
          </p>

          <p>
            By using this application, you acknowledge that:
          </p>

          <ul className="list-disc list-inside space-y-2 ml-4">
            <li>All AI-generated content requires human verification</li>
            <li>You are responsible for validating all outputs before use</li>
            <li>The application is provided "as-is" without warranties</li>
            <li>No data is stored after processing (zero data retention)</li>
          </ul>

          <p className="text-sm text-gray-600 dark:text-gray-400">
            This acknowledgment is required each session for your protection.
          </p>
        </div>

        <button
          onClick={handleAcknowledge}
          className="w-full py-3 px-4 bg-blue-600 text-white rounded-lg font-medium hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 transition-colors"
          aria-label="I agree this is AI and I will verify outputs"
        >
          I agree this is AI and I will verify outputs
        </button>
      </div>
    </div>
  )
}

